name: TailwindCss-Output-Builder

on: push
permissions:
  contents: write

jobs:
    builder:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                node-version: 18

            - name: Build output
              run: |
                npm ci
                npx tailwindcss -i ./src/css/input.css -o ./src/css/output.css

            - name: Commit output
              run: |
                git config --global user.name 'TheoCvg'
                git config --global user.email 'TheoCvg@users.noreply.github.com'
                git commit -am "Automated output"
                git push
            - run: echo "Finished building."

            
