name: TailwindCss-Output-Builder
on: push
jobs:
    builder:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                node-version: 18
            - run: npm ci
            - run: npx tailwindcss -i ./src/css/input.css -o ./src/css/output.css
            - run: echo "Finished building."

            
